### PR TITLE
Skip some cards or lists depending on source

### PR DESCRIPTION
**Pull request by ys**
Current sources for onboarding:
can be defined in data.json in your docs repo.

just add `onboarding_sources:[{id:'sfdc', title:'From SFDC'}]`
this will add an item under `onboarding New hire` with `from SFDC`

This is reflected in the recruiting source.

How to create a list or card that will work only for sfdc?
---------------------------------------------------------

```
# First Day
## Only for sfdc [sfdc]
```

The part into brackets serves as tags.

### CODE REVIEW

**Comment by jroes** [comment]
Sweet! Does it make sense to throw some documentation on this feature somewhere?

**Comment by ys** [comment]
I plan on adding some.

**Comment by jroes** [comment]
Cool. Did you want to make that part of this PR, or just something in the future?

**Comment by ys** [comment]
I think this can be an undocumented feature here first.

**Pull request merged**
