### PR TITLE
Call Trello API in series when creating checkitems

### PR DESCRIPTION
**Pull request by bensymonds**
(See commits for details.)

Trello currently has a race condition where simultaneous creation of checkitems in the same checklist can result in some checkitems not being created properly. Until they fix it we force them to be created one at a time.

### CODE REVIEW

**Comment by beanieboi** [comment]
hey 👋 could you please add a PR description. That way it's easier to know why we did things when we dig into the code history on GitHub

**Comment by bensymonds** [comment]
Ah yeah, sorry, I'm used to describing everything in the commits, so they're stored in the git repo itself rather than github, and so you don't have to open github to see what's going on. But I at least could have said that in the PR description. I've actually copied the last commit description to the PR description given that summarises the point of the PR anyway.

**Comment by beanieboi** [comment]
I think it is important to have a summary for the reviewer that describes what this PR is about and why we do it. Commit description describe on a technical level what happened in that specific commit. If a PR is composed of various commits, it's is hard to read every single commit message

**Comment by bensymonds** [comment]
Yeah actually I would probably have put a more detailed PR description if the actual change spanned several commits. But in this case each commit is completely standalone so it seemed less important. Obviously this is subjective - this was just what I'm used to from previous teams and given there was no PR description template I didn't do anything different.

As for it being hard reading commit messages - well a good set of commits will have useful descriptions which should make the PR a lot easier to review. I think if the author suggests in the PR description that the reviewer should look at the commits (which I neglected to do but should have) that's a good indication that the commit description are worth reading.

**Pull request merged**
